name: Hossein Sadeghi
description: I'm a skilled Full Stack Engineer with 7+ years of experience. I always like to bring new technologies and knowledge into work for solving problems.
socials:
  - name: LinkedIn
    icon: FaLinkedinIn
    url: https://www.linkedin.com/in/hossein-sadeghiam/
  - name: GitHub
    icon: FaGithubAlt
    url: https://github.com/Hossein-s
  - name: Medium
    icon: FaMedium
    url: https://medium.com/@hossein-sadeghi
experiences:
  - position: SOFTWARE ENGINEER
    company: CHARGEPOINT
    period: AUG 2022 - CURRENT
    current: true
  - position: FREELANCE FULL-STACK ENGINEER
    company: Biztree
    period: SEP 2021 – AUG 2022
    current: false
  - position: SENIOR SOFTWARE ENGINEER
    company: SKYROOM - ONLINE COMMUNICATIONS
    period: MAY 2019 – SEP 2021
    current: false
  - position: SOFTWARE ENGINEER
    company: SKYROOM - ONLINE COMMUNICATIONS
    period: MAR 2017 – SEP 2021
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: HAMYARSINA
    period: DEC 2016 – JAN 2017
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: JOBDO
    period: SEP 2016 – NOV 2016
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: SHAKIBI BTM
    period: JUN 2016 – JUL 2016
    current: false
  - position: BSc IN COMPUTER ENGINEERING
    company: Shahrood University of Technology
    period: NOV 2014 – JUL 2018
    current: false
skills:
  - categoryName: Languages
    items:
      - name: TypeScript
        image: /icons/TypeScript.svg
      - name: JavaScript
        image: /icons/JavaScript.svg
      - name: PHP
        image: /icons/PHP.svg
  - categoryName: Databases
    items:
      - name: PostgreSQL
        image: /icons/PostgreSQL.svg
      - name: MySQL
        image: /icons/MySQL.svg
      - name: MongoDB
        image: /icons/MongoDB.svg
      - name: Redis
        image: /icons/Redis.svg
  - categoryName: Frameworks & Libraries
    items:
      - name: NestJS
        image: /icons/NestJS.svg
      - name: mediasoup (WebRTC)
        image: /icons/mediasoup.svg
      - name: Symfony
        image: /icons/Symfony.svg
      - name: Socket.io
        image: /icons/Socket.io.svg
      - name: Express
        image: /icons/Express.svg
      - name: Fastify
        image: /icons/Fastify.svg
  - categoryName: Tools
    items:
      - name: Git
        image: /icons/Git.svg
      - name: Docker
        image: /icons/Docker.svg
      - name: Kubernetes
        image: /icons/Kubernetes.svg
      - name: Skaffold
        image: /icons/Skaffold.svg
      - name: Kafka
        image: /icons/Kafka.svg
      - name: RabbitMQ
        image: /icons/RabbitMQ.svg
      - name: Centrifugo
        image: /icons/Centrifugo.svg
      - name: AWS
        image: /icons/AWS.svg
      - name: Kong
        image: /icons/Kong.svg
  - categoryName: Frontend
    items:
      - name: React
        image: /icons/React.svg
      - name: Vue
        image: /icons/Vue.svg
