name: Hossein Sadeghi
title: Software Engineer
description: I'm a skilled Full Stack Engineer with 7+ years of experience. I always like to bring new technologies and knowledge into work for solving problems.
socials:
  - name: LinkedIn
    icon: /icons/socials/LinkedIn.svg
    url: https://www.linkedin.com/in/hossein-sadeghiam/
  - name: GitHub
    icon: /icons/socials/GitHub.svg
    url: https://github.com/Hossein-s
  - name: Medium
    icon: /icons/socials/Medium.svg
    url: https://medium.com/@hossein-sadeghi
experiences:
  - position: SENIOR SOFTWARE ENGINEER
    company: GetYourGuide
    period: MAR 2024 - CURRENT
    current: true
  - position: SOFTWARE ENGINEER
    company: CHARGEPOINT
    period: AUG 2022 - FEB 2024
    current: false
  - position: FREELANCE FULL-STACK ENGINEER
    company: Biztree
    period: SEP 2021 – AUG 2022
    current: false
  - position: SENIOR SOFTWARE ENGINEER
    company: SKYROOM – ONLINE COMMUNICATIONS
    period: MAY 2019 – SEP 2021
    current: false
  - position: SOFTWARE ENGINEER
    company: SKYROOM – ONLINE COMMUNICATIONS
    period: MAR 2017 – SEP 2021
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: HAMYARSINA
    period: DEC 2016 – JAN 2017
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: JOBDO
    period: SEP 2016 – NOV 2016
    current: false
  - position: FREELANCE FULL-STACK DEVELOPER
    company: SHAKIBI BTM
    period: JUN 2016 – JUL 2016
    current: false
  - position: BSc IN COMPUTER ENGINEERING
    company: Shahrood University of Technology
    period: NOV 2014 – JUL 2018
    current: false
skills:
  - categoryName: Languages
    items:
      - name: Kotlin
        image: /icons/skills/Kotlin.svg
      - name: TypeScript
        image: /icons/skills/TypeScript.svg
      - name: JavaScript
        image: /icons/skills/JavaScript.svg
      - name: PHP
        image: /icons/skills/PHP.svg
  - categoryName: Frameworks & Libraries
    items:
      - name: Spring Boot
        image: /icons/skills/Spring Boot.svg
      - name: NestJS
        image: /icons/skills/NestJS.svg
      - name: Symfony
        image: /icons/skills/Symfony.svg
      - name: React
        image: /icons/skills/React.svg
      - name: Vue
        image: /icons/skills/Vue.svg
      - name: Socket.io
        image: /icons/skills/Socket.io.svg
      - name: Fastify
        image: /icons/skills/Fastify.svg
      - name: mediasoup
        image: /icons/skills/mediasoup.svg
  - categoryName: Databases
    items:
      - name: PostgreSQL
        image: /icons/skills/PostgreSQL.svg
      - name: MySQL
        image: /icons/skills/MySQL.svg
      - name: MongoDB
        image: /icons/skills/MongoDB.svg
      - name: Redis
        image: /icons/skills/Redis.svg
  - categoryName: Tools
    items:
      - name: Git
        image: /icons/skills/Git.svg
      - name: Docker
        image: /icons/skills/Docker.svg
      - name: Kubernetes
        image: /icons/skills/Kubernetes.svg
      - name: Skaffold
        image: /icons/skills/Skaffold.svg
      - name: Kafka
        image: /icons/skills/Kafka.svg
      - name: RabbitMQ
        image: /icons/skills/RabbitMQ.svg
      - name: Centrifugo
        image: /icons/skills/Centrifugo.svg
      - name: AWS
        image: /icons/skills/AWS.svg
      - name: Kong
        image: /icons/skills/Kong.svg
